import { IJob } from '@types';

export const mockJobs: IJob[] = [
	{
		company: {
			name: 'Holland & Barrett',
			logo: '/assets/companies/holland-and-barrett.svg',
			url: 'https://www.hollandandbarrett.com/',

			city: '',
			country: '',
			location: '',
		},
		location: '',
		jobTitle: 'Software Engineer',
		startDate: '2020-08-10',
		endDate: null,
		technologies: [
			'TypeScript',
			'React',
			'Next.js',
			'Redux',
			'GraphQL',
			'REST API',
			'Jest',
			'Cypress',
		],
		summary: [],
	},
	{
		company: {
			name: 'Holland & Barrett',
			logo: '/assets/companies/holland-and-barrett.svg',
			url: 'https://www.hollandandbarrett.com/',
			location: '',
			country: '',
			city: '',
		},
		location: '',
		summary: [],
		jobTitle: 'Software Engineer',
		startDate: 'Aug 2020',
		endDate: 'present',
		technologies: [
			'TypeScript',
			'React',
			'Next.js',
			'Redux',
			'GraphQL',
			'REST API',
			'Jest',
			'Cypress',
		],
	},
	{
		company: {
			name: 'Holland & Barrett',
			logo: '/assets/companies/holland-and-barrett.svg',
			url: 'https://www.hollandandbarrett.com/',
			location: '',
			country: '',
			city: '',
		},
		location: '',
		summary: [],
		jobTitle: 'Software Engineer',
		startDate: 'Aug 2020',
		endDate: 'present',
		technologies: [
			'TypeScript',
			'React',
			'Next.js',
			'Redux',
			'GraphQL',
			'REST API',
			'Jest',
			'Cypress',
		],
	},
];
